spring:
  datasource:
     url: jdbc:mysql://localhost:3306/rfid?serverTimezone=CTT&characterEncoding=UTF-8
     username: root

#     password: Goldenwind666
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
     max-active: 200
     max-idle: 20
     min-idle: 10
  thymeleaf:
     cache: false
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 20MB

server:
  port: 8090
  connectionTimeout: 180000
  max-http-header-size: 4048576
  tomcat:
    max-http-post-size: 1000MB

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml

